@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Nov 16 16:49:26 +0530 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim pipeline_tb_behav -key {Behavioral:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view D:/Semesters/Sem3/ES203/ES203_Project/ES203_project_final/pipeline_tb_behav.wcfg -log simulate.log"
call xsim  pipeline_tb_behav -key {Behavioral:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view D:/Semesters/Sem3/ES203/ES203_Project/ES203_project_final/pipeline_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
